feat(e2e): Add e2e-test suit for device-localpv
openebs-archive/device-localpv pull request #22
Opened 2021-06-30 17:48 UTC by w3aman

Signed-off-by: w3aman <aman.gupta@mayadata.io>

- This PR adds e2e-test suit for device-localpv

2021-06-30 17:49 UTC, w3aman commented
cc: @nsathyaseelan for review

2021-07-12 09:51 UTC, nsathyaseelan requested changes

2021-07-12 09:51 UTC, nsathyaseelan commented on e2e-tests/Dockerfile
> +
@w3aman  can you add this dependent package before openshift package installation `RUN pip install ruamel.yaml.clib==0.1.2`

2021-07-12 09:51 UTC, nsathyaseelan commented on e2e-tests/apps/busybox/liveness/test.yml
> +            - name: Record test instance/run ID
can we use the util already created for this task?

2021-07-12 09:51 UTC, nsathyaseelan commented on e2e-tests/apps/percona/workload/test.yml
> +                run_id: "{{ lookup('env','RUN_ID') }}"
Here also can we use the util?

2021-07-13 13:50 UTC, nsathyaseelan approved these changes
lgtm

2021-07-14 06:40 UTC, merged